---
title: "strings_and_factors"
author: "Kaitlyn Wang"
date: "10/21/2021"
output: html_document
---

```{r}
library(rvest)
library(tidyverse)
library(p8105.datasets)
```


## String vectors

```{r}
string_vec = c("my", "name", "is", "kaitlyn")

str_detect(string_vec, "kaitlyn")

str_replace(string_vec, "kaitlyn", "Kaitlyn")
str_replace(string_vec, "e", "this is the letter e")
```


```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think")
str_detect(string_vec, "i think$")
```

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Bb]ush")
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]")

string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11")
```


```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")

```


## Why factors are weird

```{r}
factor_vec = factor(c("male", "male", "female", "female"))

as.numeric(factor_vec)

factor_vec = fct_relevel(factor_vec, "male")
as.numeric(factor_vec)
```


## NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj = 
  read_html(nsduh_url) %>% 
  html_table() %>% 
  first() %>% 
  slice(-1)
```

Let's clean this up!

```{r}
marj_df = 
  table_marj %>% 
    select(-contains("P value")) %>% 
    pivot_longer(
      -State, 
      names_to = "age_year",
      values_to = "percent") %>% 
    separate(age_year, into = c("age", "year"), "\\(") %>% 
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent)) %>% 
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```

Do dataframe stuff

```{r}
marj_df %>% 
  filter(age == "12-17") %>% 
  mutate(
    State = fct_reorder(State, percent)) %>% 
  ggplot(aes(x = State, y = percent, color = year)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```


## Restarurant Inspections

```{r}
data("rest_inspec")
```

```{r}
rest_inspec %>% 
  janitor::tabyl(boro, grade)
```

```{r}
rest_inspec =
  rest_inspec %>% 
  filter(
    str_detect(grade, "[ABC]", 
    !(boro == "Missing"))) %>% 
  mutate(boro == str_to_title(boro))
```

```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>% 
  mutate(
    boro = fct_infreq(boro)
  ) %>% 
  ggplot(aes(x = boro, fill = grade)) + geom_bar()
```

What about changing a label ... 

```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>% 
  mutate(
    boro = fct_infreq(boro),
    boro = str_replace(boro, "Manhattan", "The City")
  ) %>% 
  ggplot(aes(x = boro, fill = grade)) + geom_bar()
```

```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  pivot_wider(names_from = grade, values_from = n)

rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>%
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar() 
```

